### ISSUE TITLE
Pinned cookbook dependency versions hang Librarian

### ISSUE THREAD

**Issue by hectcastro** [basho/riak-cs-chef-cookbook#44]
If cookbook dependency version constraints use `~>`, it causes [Librarian](https://github.com/applicationsonline/librarian-chef) to eat 100% CPU and hang.

This issue was split out of https://github.com/basho/riak-cs-chef-cookbook/pull/43.

/cc @zquestz

**Comment by cheeseplus** [comment]
Closing this one as won-fix for now but if someone really wants Librarian support and can prove this isn't a bug with Librarian then feel free to re-open.
